/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfissionalRouteImport } from './routes/profissional'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GlossarioRouteImport } from './routes/glossario'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewIndexRouteImport } from './routes/preview.index'
import { Route as JornadasIndexRouteImport } from './routes/jornadas.index'
import { Route as GuiasIndexRouteImport } from './routes/guias.index'
import { Route as AcordosIndexRouteImport } from './routes/acordos.index'
import { Route as SobreDrMarcosRouteImport } from './routes/sobre.dr-marcos'
import { Route as PreviewProfissionalRouteImport } from './routes/preview.profissional'
import { Route as PreviewHomeRouteImport } from './routes/preview.home'
import { Route as PreviewGuiasRouteImport } from './routes/preview.guias'
import { Route as JornadasJornadaRouteImport } from './routes/jornadas.$jornada'
import { Route as GuiasSlugRouteImport } from './routes/guias.$slug'
import { Route as AcordosPaisRouteImport } from './routes/acordos.$pais'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as PreviewJornadasIndexRouteImport } from './routes/preview.jornadas.index'
import { Route as AuthenticatedHubIndexRouteImport } from './routes/_authenticated/hub.index'
import { Route as PreviewJornadasJornadaRouteImport } from './routes/preview.jornadas.$jornada'
import { Route as PreviewGuiasSaidaDefinitivaDoPaisRouteImport } from './routes/preview.guias.saida-definitiva-do-pais'
import { Route as AuthenticatedHubCalculadoraRouteImport } from './routes/_authenticated/hub.calculadora'
import { Route as AuthenticatedHubPaisRouteImport } from './routes/_authenticated/hub.$pais'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionalRoute = ProfissionalRouteImport.update({
  id: '/profissional',
  path: '/profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarioRoute = GlossarioRouteImport.update({
  id: '/glossario',
  path: '/glossario',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewIndexRoute = PreviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreviewRoute,
} as any)
const JornadasIndexRoute = JornadasIndexRouteImport.update({
  id: '/jornadas/',
  path: '/jornadas/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasIndexRoute = GuiasIndexRouteImport.update({
  id: '/guias/',
  path: '/guias/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcordosIndexRoute = AcordosIndexRouteImport.update({
  id: '/acordos/',
  path: '/acordos/',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreDrMarcosRoute = SobreDrMarcosRouteImport.update({
  id: '/sobre/dr-marcos',
  path: '/sobre/dr-marcos',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewProfissionalRoute = PreviewProfissionalRouteImport.update({
  id: '/profissional',
  path: '/profissional',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewHomeRoute = PreviewHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewGuiasRoute = PreviewGuiasRouteImport.update({
  id: '/guias',
  path: '/guias',
  getParentRoute: () => PreviewRoute,
} as any)
const JornadasJornadaRoute = JornadasJornadaRouteImport.update({
  id: '/jornadas/$jornada',
  path: '/jornadas/$jornada',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasSlugRoute = GuiasSlugRouteImport.update({
  id: '/guias/$slug',
  path: '/guias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AcordosPaisRoute = AcordosPaisRouteImport.update({
  id: '/acordos/$pais',
  path: '/acordos/$pais',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PreviewJornadasIndexRoute = PreviewJornadasIndexRouteImport.update({
  id: '/jornadas/',
  path: '/jornadas/',
  getParentRoute: () => PreviewRoute,
} as any)
const AuthenticatedHubIndexRoute = AuthenticatedHubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PreviewJornadasJornadaRoute = PreviewJornadasJornadaRouteImport.update({
  id: '/jornadas/$jornada',
  path: '/jornadas/$jornada',
  getParentRoute: () => PreviewRoute,
} as any)
const PreviewGuiasSaidaDefinitivaDoPaisRoute =
  PreviewGuiasSaidaDefinitivaDoPaisRouteImport.update({
    id: '/saida-definitiva-do-pais',
    path: '/saida-definitiva-do-pais',
    getParentRoute: () => PreviewGuiasRoute,
  } as any)
const AuthenticatedHubCalculadoraRoute =
  AuthenticatedHubCalculadoraRouteImport.update({
    id: '/hub/calculadora',
    path: '/hub/calculadora',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHubPaisRoute = AuthenticatedHubPaisRouteImport.update({
  id: '/hub/$pais',
  path: '/hub/$pais',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cadastro': typeof CadastroRoute
  '/calculadora': typeof CalculadoraRoute
  '/contato': typeof ContatoRoute
  '/glossario': typeof GlossarioRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/preview': typeof PreviewRouteWithChildren
  '/profissional': typeof ProfissionalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/conta': typeof AuthenticatedContaRoute
  '/acordos/$pais': typeof AcordosPaisRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/jornadas/$jornada': typeof JornadasJornadaRoute
  '/preview/guias': typeof PreviewGuiasRouteWithChildren
  '/preview/home': typeof PreviewHomeRoute
  '/preview/profissional': typeof PreviewProfissionalRoute
  '/sobre/dr-marcos': typeof SobreDrMarcosRoute
  '/acordos/': typeof AcordosIndexRoute
  '/guias/': typeof GuiasIndexRoute
  '/jornadas/': typeof JornadasIndexRoute
  '/preview/': typeof PreviewIndexRoute
  '/hub/$pais': typeof AuthenticatedHubPaisRoute
  '/hub/calculadora': typeof AuthenticatedHubCalculadoraRoute
  '/preview/guias/saida-definitiva-do-pais': typeof PreviewGuiasSaidaDefinitivaDoPaisRoute
  '/preview/jornadas/$jornada': typeof PreviewJornadasJornadaRoute
  '/hub/': typeof AuthenticatedHubIndexRoute
  '/preview/jornadas/': typeof PreviewJornadasIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cadastro': typeof CadastroRoute
  '/calculadora': typeof CalculadoraRoute
  '/contato': typeof ContatoRoute
  '/glossario': typeof GlossarioRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/profissional': typeof ProfissionalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/conta': typeof AuthenticatedContaRoute
  '/acordos/$pais': typeof AcordosPaisRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/jornadas/$jornada': typeof JornadasJornadaRoute
  '/preview/guias': typeof PreviewGuiasRouteWithChildren
  '/preview/home': typeof PreviewHomeRoute
  '/preview/profissional': typeof PreviewProfissionalRoute
  '/sobre/dr-marcos': typeof SobreDrMarcosRoute
  '/acordos': typeof AcordosIndexRoute
  '/guias': typeof GuiasIndexRoute
  '/jornadas': typeof JornadasIndexRoute
  '/preview': typeof PreviewIndexRoute
  '/hub/$pais': typeof AuthenticatedHubPaisRoute
  '/hub/calculadora': typeof AuthenticatedHubCalculadoraRoute
  '/preview/guias/saida-definitiva-do-pais': typeof PreviewGuiasSaidaDefinitivaDoPaisRoute
  '/preview/jornadas/$jornada': typeof PreviewJornadasJornadaRoute
  '/hub': typeof AuthenticatedHubIndexRoute
  '/preview/jornadas': typeof PreviewJornadasIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/blog': typeof BlogRoute
  '/cadastro': typeof CadastroRoute
  '/calculadora': typeof CalculadoraRoute
  '/contato': typeof ContatoRoute
  '/glossario': typeof GlossarioRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/preview': typeof PreviewRouteWithChildren
  '/profissional': typeof ProfissionalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/acordos/$pais': typeof AcordosPaisRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/jornadas/$jornada': typeof JornadasJornadaRoute
  '/preview/guias': typeof PreviewGuiasRouteWithChildren
  '/preview/home': typeof PreviewHomeRoute
  '/preview/profissional': typeof PreviewProfissionalRoute
  '/sobre/dr-marcos': typeof SobreDrMarcosRoute
  '/acordos/': typeof AcordosIndexRoute
  '/guias/': typeof GuiasIndexRoute
  '/jornadas/': typeof JornadasIndexRoute
  '/preview/': typeof PreviewIndexRoute
  '/_authenticated/hub/$pais': typeof AuthenticatedHubPaisRoute
  '/_authenticated/hub/calculadora': typeof AuthenticatedHubCalculadoraRoute
  '/preview/guias/saida-definitiva-do-pais': typeof PreviewGuiasSaidaDefinitivaDoPaisRoute
  '/preview/jornadas/$jornada': typeof PreviewJornadasJornadaRoute
  '/_authenticated/hub/': typeof AuthenticatedHubIndexRoute
  '/preview/jornadas/': typeof PreviewJornadasIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/cadastro'
    | '/calculadora'
    | '/contato'
    | '/glossario'
    | '/login'
    | '/precos'
    | '/preview'
    | '/profissional'
    | '/reset-password'
    | '/conta'
    | '/acordos/$pais'
    | '/guias/$slug'
    | '/jornadas/$jornada'
    | '/preview/guias'
    | '/preview/home'
    | '/preview/profissional'
    | '/sobre/dr-marcos'
    | '/acordos/'
    | '/guias/'
    | '/jornadas/'
    | '/preview/'
    | '/hub/$pais'
    | '/hub/calculadora'
    | '/preview/guias/saida-definitiva-do-pais'
    | '/preview/jornadas/$jornada'
    | '/hub/'
    | '/preview/jornadas/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/cadastro'
    | '/calculadora'
    | '/contato'
    | '/glossario'
    | '/login'
    | '/precos'
    | '/profissional'
    | '/reset-password'
    | '/conta'
    | '/acordos/$pais'
    | '/guias/$slug'
    | '/jornadas/$jornada'
    | '/preview/guias'
    | '/preview/home'
    | '/preview/profissional'
    | '/sobre/dr-marcos'
    | '/acordos'
    | '/guias'
    | '/jornadas'
    | '/preview'
    | '/hub/$pais'
    | '/hub/calculadora'
    | '/preview/guias/saida-definitiva-do-pais'
    | '/preview/jornadas/$jornada'
    | '/hub'
    | '/preview/jornadas'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/blog'
    | '/cadastro'
    | '/calculadora'
    | '/contato'
    | '/glossario'
    | '/login'
    | '/precos'
    | '/preview'
    | '/profissional'
    | '/reset-password'
    | '/_authenticated/conta'
    | '/acordos/$pais'
    | '/guias/$slug'
    | '/jornadas/$jornada'
    | '/preview/guias'
    | '/preview/home'
    | '/preview/profissional'
    | '/sobre/dr-marcos'
    | '/acordos/'
    | '/guias/'
    | '/jornadas/'
    | '/preview/'
    | '/_authenticated/hub/$pais'
    | '/_authenticated/hub/calculadora'
    | '/preview/guias/saida-definitiva-do-pais'
    | '/preview/jornadas/$jornada'
    | '/_authenticated/hub/'
    | '/preview/jornadas/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BlogRoute: typeof BlogRoute
  CadastroRoute: typeof CadastroRoute
  CalculadoraRoute: typeof CalculadoraRoute
  ContatoRoute: typeof ContatoRoute
  GlossarioRoute: typeof GlossarioRoute
  LoginRoute: typeof LoginRoute
  PrecosRoute: typeof PrecosRoute
  PreviewRoute: typeof PreviewRouteWithChildren
  ProfissionalRoute: typeof ProfissionalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AcordosPaisRoute: typeof AcordosPaisRoute
  GuiasSlugRoute: typeof GuiasSlugRoute
  JornadasJornadaRoute: typeof JornadasJornadaRoute
  SobreDrMarcosRoute: typeof SobreDrMarcosRoute
  AcordosIndexRoute: typeof AcordosIndexRoute
  GuiasIndexRoute: typeof GuiasIndexRoute
  JornadasIndexRoute: typeof JornadasIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissional': {
      id: '/profissional'
      path: '/profissional'
      fullPath: '/profissional'
      preLoaderRoute: typeof ProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario': {
      id: '/glossario'
      path: '/glossario'
      fullPath: '/glossario'
      preLoaderRoute: typeof GlossarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/': {
      id: '/preview/'
      path: '/'
      fullPath: '/preview/'
      preLoaderRoute: typeof PreviewIndexRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/jornadas/': {
      id: '/jornadas/'
      path: '/jornadas'
      fullPath: '/jornadas/'
      preLoaderRoute: typeof JornadasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/': {
      id: '/guias/'
      path: '/guias'
      fullPath: '/guias/'
      preLoaderRoute: typeof GuiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acordos/': {
      id: '/acordos/'
      path: '/acordos'
      fullPath: '/acordos/'
      preLoaderRoute: typeof AcordosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre/dr-marcos': {
      id: '/sobre/dr-marcos'
      path: '/sobre/dr-marcos'
      fullPath: '/sobre/dr-marcos'
      preLoaderRoute: typeof SobreDrMarcosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/profissional': {
      id: '/preview/profissional'
      path: '/profissional'
      fullPath: '/preview/profissional'
      preLoaderRoute: typeof PreviewProfissionalRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/home': {
      id: '/preview/home'
      path: '/home'
      fullPath: '/preview/home'
      preLoaderRoute: typeof PreviewHomeRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/guias': {
      id: '/preview/guias'
      path: '/guias'
      fullPath: '/preview/guias'
      preLoaderRoute: typeof PreviewGuiasRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/jornadas/$jornada': {
      id: '/jornadas/$jornada'
      path: '/jornadas/$jornada'
      fullPath: '/jornadas/$jornada'
      preLoaderRoute: typeof JornadasJornadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/$slug': {
      id: '/guias/$slug'
      path: '/guias/$slug'
      fullPath: '/guias/$slug'
      preLoaderRoute: typeof GuiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acordos/$pais': {
      id: '/acordos/$pais'
      path: '/acordos/$pais'
      fullPath: '/acordos/$pais'
      preLoaderRoute: typeof AcordosPaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/preview/jornadas/': {
      id: '/preview/jornadas/'
      path: '/jornadas'
      fullPath: '/preview/jornadas/'
      preLoaderRoute: typeof PreviewJornadasIndexRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/_authenticated/hub/': {
      id: '/_authenticated/hub/'
      path: '/hub'
      fullPath: '/hub/'
      preLoaderRoute: typeof AuthenticatedHubIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/preview/jornadas/$jornada': {
      id: '/preview/jornadas/$jornada'
      path: '/jornadas/$jornada'
      fullPath: '/preview/jornadas/$jornada'
      preLoaderRoute: typeof PreviewJornadasJornadaRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/preview/guias/saida-definitiva-do-pais': {
      id: '/preview/guias/saida-definitiva-do-pais'
      path: '/saida-definitiva-do-pais'
      fullPath: '/preview/guias/saida-definitiva-do-pais'
      preLoaderRoute: typeof PreviewGuiasSaidaDefinitivaDoPaisRouteImport
      parentRoute: typeof PreviewGuiasRoute
    }
    '/_authenticated/hub/calculadora': {
      id: '/_authenticated/hub/calculadora'
      path: '/hub/calculadora'
      fullPath: '/hub/calculadora'
      preLoaderRoute: typeof AuthenticatedHubCalculadoraRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hub/$pais': {
      id: '/_authenticated/hub/$pais'
      path: '/hub/$pais'
      fullPath: '/hub/$pais'
      preLoaderRoute: typeof AuthenticatedHubPaisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedHubPaisRoute: typeof AuthenticatedHubPaisRoute
  AuthenticatedHubCalculadoraRoute: typeof AuthenticatedHubCalculadoraRoute
  AuthenticatedHubIndexRoute: typeof AuthenticatedHubIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedHubPaisRoute: AuthenticatedHubPaisRoute,
  AuthenticatedHubCalculadoraRoute: AuthenticatedHubCalculadoraRoute,
  AuthenticatedHubIndexRoute: AuthenticatedHubIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PreviewGuiasRouteChildren {
  PreviewGuiasSaidaDefinitivaDoPaisRoute: typeof PreviewGuiasSaidaDefinitivaDoPaisRoute
}

const PreviewGuiasRouteChildren: PreviewGuiasRouteChildren = {
  PreviewGuiasSaidaDefinitivaDoPaisRoute:
    PreviewGuiasSaidaDefinitivaDoPaisRoute,
}

const PreviewGuiasRouteWithChildren = PreviewGuiasRoute._addFileChildren(
  PreviewGuiasRouteChildren,
)

interface PreviewRouteChildren {
  PreviewGuiasRoute: typeof PreviewGuiasRouteWithChildren
  PreviewHomeRoute: typeof PreviewHomeRoute
  PreviewProfissionalRoute: typeof PreviewProfissionalRoute
  PreviewIndexRoute: typeof PreviewIndexRoute
  PreviewJornadasJornadaRoute: typeof PreviewJornadasJornadaRoute
  PreviewJornadasIndexRoute: typeof PreviewJornadasIndexRoute
}

const PreviewRouteChildren: PreviewRouteChildren = {
  PreviewGuiasRoute: PreviewGuiasRouteWithChildren,
  PreviewHomeRoute: PreviewHomeRoute,
  PreviewProfissionalRoute: PreviewProfissionalRoute,
  PreviewIndexRoute: PreviewIndexRoute,
  PreviewJornadasJornadaRoute: PreviewJornadasJornadaRoute,
  PreviewJornadasIndexRoute: PreviewJornadasIndexRoute,
}

const PreviewRouteWithChildren =
  PreviewRoute._addFileChildren(PreviewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BlogRoute: BlogRoute,
  CadastroRoute: CadastroRoute,
  CalculadoraRoute: CalculadoraRoute,
  ContatoRoute: ContatoRoute,
  GlossarioRoute: GlossarioRoute,
  LoginRoute: LoginRoute,
  PrecosRoute: PrecosRoute,
  PreviewRoute: PreviewRouteWithChildren,
  ProfissionalRoute: ProfissionalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AcordosPaisRoute: AcordosPaisRoute,
  GuiasSlugRoute: GuiasSlugRoute,
  JornadasJornadaRoute: JornadasJornadaRoute,
  SobreDrMarcosRoute: SobreDrMarcosRoute,
  AcordosIndexRoute: AcordosIndexRoute,
  GuiasIndexRoute: GuiasIndexRoute,
  JornadasIndexRoute: JornadasIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
