/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfissionalRouteImport } from './routes/profissional'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GlossarioRouteImport } from './routes/glossario'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JornadasIndexRouteImport } from './routes/jornadas.index'
import { Route as GuiasIndexRouteImport } from './routes/guias.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AcordosIndexRouteImport } from './routes/acordos.index'
import { Route as SobreDrMarcosRouteImport } from './routes/sobre.dr-marcos'
import { Route as JornadasJornadaRouteImport } from './routes/jornadas.$jornada'
import { Route as GuiasSaidaDefinitivaDoPaisRouteImport } from './routes/guias.saida-definitiva-do-pais'
import { Route as GuiasSlugRouteImport } from './routes/guias.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AcordosPaisRouteImport } from './routes/acordos.$pais'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedHubIndexRouteImport } from './routes/_authenticated/hub.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicContatoRouteImport } from './routes/api/public/contato'
import { Route as ApiPublicCalcLeadRouteImport } from './routes/api/public/calc-lead'
import { Route as AuthenticatedHubLeadsRouteImport } from './routes/_authenticated/hub.leads'
import { Route as AuthenticatedHubLaudosRouteImport } from './routes/_authenticated/hub.laudos'
import { Route as AuthenticatedHubLaudoRouteImport } from './routes/_authenticated/hub.laudo'
import { Route as AuthenticatedHubCuponsRouteImport } from './routes/_authenticated/hub.cupons'
import { Route as AuthenticatedHubCalculadoraRouteImport } from './routes/_authenticated/hub.calculadora'
import { Route as AuthenticatedHubBlogRouteImport } from './routes/_authenticated/hub.blog'
import { Route as AuthenticatedHubPaisRouteImport } from './routes/_authenticated/hub.$pais'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksBlogGenRouteImport } from './routes/api/public/hooks/blog-gen'
import { Route as AuthenticatedHubBlogSlugRouteImport } from './routes/_authenticated/hub.blog.$slug'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionalRoute = ProfissionalRouteImport.update({
  id: '/profissional',
  path: '/profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarioRoute = GlossarioRouteImport.update({
  id: '/glossario',
  path: '/glossario',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadasIndexRoute = JornadasIndexRouteImport.update({
  id: '/jornadas/',
  path: '/jornadas/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasIndexRoute = GuiasIndexRouteImport.update({
  id: '/guias/',
  path: '/guias/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcordosIndexRoute = AcordosIndexRouteImport.update({
  id: '/acordos/',
  path: '/acordos/',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreDrMarcosRoute = SobreDrMarcosRouteImport.update({
  id: '/sobre/dr-marcos',
  path: '/sobre/dr-marcos',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadasJornadaRoute = JornadasJornadaRouteImport.update({
  id: '/jornadas/$jornada',
  path: '/jornadas/$jornada',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasSaidaDefinitivaDoPaisRoute =
  GuiasSaidaDefinitivaDoPaisRouteImport.update({
    id: '/guias/saida-definitiva-do-pais',
    path: '/guias/saida-definitiva-do-pais',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuiasSlugRoute = GuiasSlugRouteImport.update({
  id: '/guias/$slug',
  path: '/guias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AcordosPaisRoute = AcordosPaisRouteImport.update({
  id: '/acordos/$pais',
  path: '/acordos/$pais',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHubIndexRoute = AuthenticatedHubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContatoRoute = ApiPublicContatoRouteImport.update({
  id: '/api/public/contato',
  path: '/api/public/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCalcLeadRoute = ApiPublicCalcLeadRouteImport.update({
  id: '/api/public/calc-lead',
  path: '/api/public/calc-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHubLeadsRoute = AuthenticatedHubLeadsRouteImport.update({
  id: '/hub/leads',
  path: '/hub/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHubLaudosRoute = AuthenticatedHubLaudosRouteImport.update({
  id: '/hub/laudos',
  path: '/hub/laudos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHubLaudoRoute = AuthenticatedHubLaudoRouteImport.update({
  id: '/hub/laudo',
  path: '/hub/laudo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHubCuponsRoute = AuthenticatedHubCuponsRouteImport.update({
  id: '/hub/cupons',
  path: '/hub/cupons',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHubCalculadoraRoute =
  AuthenticatedHubCalculadoraRouteImport.update({
    id: '/hub/calculadora',
    path: '/hub/calculadora',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHubBlogRoute = AuthenticatedHubBlogRouteImport.update({
  id: '/hub/blog',
  path: '/hub/blog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHubPaisRoute = AuthenticatedHubPaisRouteImport.update({
  id: '/hub/$pais',
  path: '/hub/$pais',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBlogGenRoute = ApiPublicHooksBlogGenRouteImport.update({
  id: '/api/public/hooks/blog-gen',
  path: '/api/public/hooks/blog-gen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHubBlogSlugRoute =
  AuthenticatedHubBlogSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedHubBlogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/calculadora': typeof CalculadoraRoute
  '/contato': typeof ContatoRoute
  '/glossario': typeof GlossarioRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/profissional': typeof ProfissionalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/conta': typeof AuthenticatedContaRoute
  '/acordos/$pais': typeof AcordosPaisRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/guias/saida-definitiva-do-pais': typeof GuiasSaidaDefinitivaDoPaisRoute
  '/jornadas/$jornada': typeof JornadasJornadaRoute
  '/sobre/dr-marcos': typeof SobreDrMarcosRoute
  '/acordos/': typeof AcordosIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/guias/': typeof GuiasIndexRoute
  '/jornadas/': typeof JornadasIndexRoute
  '/hub/$pais': typeof AuthenticatedHubPaisRoute
  '/hub/blog': typeof AuthenticatedHubBlogRouteWithChildren
  '/hub/calculadora': typeof AuthenticatedHubCalculadoraRoute
  '/hub/cupons': typeof AuthenticatedHubCuponsRoute
  '/hub/laudo': typeof AuthenticatedHubLaudoRoute
  '/hub/laudos': typeof AuthenticatedHubLaudosRoute
  '/hub/leads': typeof AuthenticatedHubLeadsRoute
  '/api/public/calc-lead': typeof ApiPublicCalcLeadRoute
  '/api/public/contato': typeof ApiPublicContatoRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/hub/': typeof AuthenticatedHubIndexRoute
  '/hub/blog/$slug': typeof AuthenticatedHubBlogSlugRoute
  '/api/public/hooks/blog-gen': typeof ApiPublicHooksBlogGenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/calculadora': typeof CalculadoraRoute
  '/contato': typeof ContatoRoute
  '/glossario': typeof GlossarioRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/profissional': typeof ProfissionalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/conta': typeof AuthenticatedContaRoute
  '/acordos/$pais': typeof AcordosPaisRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/guias/saida-definitiva-do-pais': typeof GuiasSaidaDefinitivaDoPaisRoute
  '/jornadas/$jornada': typeof JornadasJornadaRoute
  '/sobre/dr-marcos': typeof SobreDrMarcosRoute
  '/acordos': typeof AcordosIndexRoute
  '/blog': typeof BlogIndexRoute
  '/guias': typeof GuiasIndexRoute
  '/jornadas': typeof JornadasIndexRoute
  '/hub/$pais': typeof AuthenticatedHubPaisRoute
  '/hub/blog': typeof AuthenticatedHubBlogRouteWithChildren
  '/hub/calculadora': typeof AuthenticatedHubCalculadoraRoute
  '/hub/cupons': typeof AuthenticatedHubCuponsRoute
  '/hub/laudo': typeof AuthenticatedHubLaudoRoute
  '/hub/laudos': typeof AuthenticatedHubLaudosRoute
  '/hub/leads': typeof AuthenticatedHubLeadsRoute
  '/api/public/calc-lead': typeof ApiPublicCalcLeadRoute
  '/api/public/contato': typeof ApiPublicContatoRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/hub': typeof AuthenticatedHubIndexRoute
  '/hub/blog/$slug': typeof AuthenticatedHubBlogSlugRoute
  '/api/public/hooks/blog-gen': typeof ApiPublicHooksBlogGenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/calculadora': typeof CalculadoraRoute
  '/contato': typeof ContatoRoute
  '/glossario': typeof GlossarioRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/profissional': typeof ProfissionalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/acordos/$pais': typeof AcordosPaisRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/guias/saida-definitiva-do-pais': typeof GuiasSaidaDefinitivaDoPaisRoute
  '/jornadas/$jornada': typeof JornadasJornadaRoute
  '/sobre/dr-marcos': typeof SobreDrMarcosRoute
  '/acordos/': typeof AcordosIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/guias/': typeof GuiasIndexRoute
  '/jornadas/': typeof JornadasIndexRoute
  '/_authenticated/hub/$pais': typeof AuthenticatedHubPaisRoute
  '/_authenticated/hub/blog': typeof AuthenticatedHubBlogRouteWithChildren
  '/_authenticated/hub/calculadora': typeof AuthenticatedHubCalculadoraRoute
  '/_authenticated/hub/cupons': typeof AuthenticatedHubCuponsRoute
  '/_authenticated/hub/laudo': typeof AuthenticatedHubLaudoRoute
  '/_authenticated/hub/laudos': typeof AuthenticatedHubLaudosRoute
  '/_authenticated/hub/leads': typeof AuthenticatedHubLeadsRoute
  '/api/public/calc-lead': typeof ApiPublicCalcLeadRoute
  '/api/public/contato': typeof ApiPublicContatoRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/hub/': typeof AuthenticatedHubIndexRoute
  '/_authenticated/hub/blog/$slug': typeof AuthenticatedHubBlogSlugRoute
  '/api/public/hooks/blog-gen': typeof ApiPublicHooksBlogGenRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/calculadora'
    | '/contato'
    | '/glossario'
    | '/login'
    | '/precos'
    | '/profissional'
    | '/reset-password'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/conta'
    | '/acordos/$pais'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/guias/$slug'
    | '/guias/saida-definitiva-do-pais'
    | '/jornadas/$jornada'
    | '/sobre/dr-marcos'
    | '/acordos/'
    | '/blog/'
    | '/guias/'
    | '/jornadas/'
    | '/hub/$pais'
    | '/hub/blog'
    | '/hub/calculadora'
    | '/hub/cupons'
    | '/hub/laudo'
    | '/hub/laudos'
    | '/hub/leads'
    | '/api/public/calc-lead'
    | '/api/public/contato'
    | '/lovable/email/suppression'
    | '/hub/'
    | '/hub/blog/$slug'
    | '/api/public/hooks/blog-gen'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/calculadora'
    | '/contato'
    | '/glossario'
    | '/login'
    | '/precos'
    | '/profissional'
    | '/reset-password'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/conta'
    | '/acordos/$pais'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/guias/$slug'
    | '/guias/saida-definitiva-do-pais'
    | '/jornadas/$jornada'
    | '/sobre/dr-marcos'
    | '/acordos'
    | '/blog'
    | '/guias'
    | '/jornadas'
    | '/hub/$pais'
    | '/hub/blog'
    | '/hub/calculadora'
    | '/hub/cupons'
    | '/hub/laudo'
    | '/hub/laudos'
    | '/hub/leads'
    | '/api/public/calc-lead'
    | '/api/public/contato'
    | '/lovable/email/suppression'
    | '/hub'
    | '/hub/blog/$slug'
    | '/api/public/hooks/blog-gen'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/calculadora'
    | '/contato'
    | '/glossario'
    | '/login'
    | '/precos'
    | '/profissional'
    | '/reset-password'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/_authenticated/conta'
    | '/acordos/$pais'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/guias/$slug'
    | '/guias/saida-definitiva-do-pais'
    | '/jornadas/$jornada'
    | '/sobre/dr-marcos'
    | '/acordos/'
    | '/blog/'
    | '/guias/'
    | '/jornadas/'
    | '/_authenticated/hub/$pais'
    | '/_authenticated/hub/blog'
    | '/_authenticated/hub/calculadora'
    | '/_authenticated/hub/cupons'
    | '/_authenticated/hub/laudo'
    | '/_authenticated/hub/laudos'
    | '/_authenticated/hub/leads'
    | '/api/public/calc-lead'
    | '/api/public/contato'
    | '/lovable/email/suppression'
    | '/_authenticated/hub/'
    | '/_authenticated/hub/blog/$slug'
    | '/api/public/hooks/blog-gen'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CalculadoraRoute: typeof CalculadoraRoute
  ContatoRoute: typeof ContatoRoute
  GlossarioRoute: typeof GlossarioRoute
  LoginRoute: typeof LoginRoute
  PrecosRoute: typeof PrecosRoute
  ProfissionalRoute: typeof ProfissionalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AcordosPaisRoute: typeof AcordosPaisRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  GuiasSlugRoute: typeof GuiasSlugRoute
  GuiasSaidaDefinitivaDoPaisRoute: typeof GuiasSaidaDefinitivaDoPaisRoute
  JornadasJornadaRoute: typeof JornadasJornadaRoute
  SobreDrMarcosRoute: typeof SobreDrMarcosRoute
  AcordosIndexRoute: typeof AcordosIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GuiasIndexRoute: typeof GuiasIndexRoute
  JornadasIndexRoute: typeof JornadasIndexRoute
  ApiPublicCalcLeadRoute: typeof ApiPublicCalcLeadRoute
  ApiPublicContatoRoute: typeof ApiPublicContatoRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksBlogGenRoute: typeof ApiPublicHooksBlogGenRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissional': {
      id: '/profissional'
      path: '/profissional'
      fullPath: '/profissional'
      preLoaderRoute: typeof ProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario': {
      id: '/glossario'
      path: '/glossario'
      fullPath: '/glossario'
      preLoaderRoute: typeof GlossarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornadas/': {
      id: '/jornadas/'
      path: '/jornadas'
      fullPath: '/jornadas/'
      preLoaderRoute: typeof JornadasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/': {
      id: '/guias/'
      path: '/guias'
      fullPath: '/guias/'
      preLoaderRoute: typeof GuiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acordos/': {
      id: '/acordos/'
      path: '/acordos'
      fullPath: '/acordos/'
      preLoaderRoute: typeof AcordosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre/dr-marcos': {
      id: '/sobre/dr-marcos'
      path: '/sobre/dr-marcos'
      fullPath: '/sobre/dr-marcos'
      preLoaderRoute: typeof SobreDrMarcosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornadas/$jornada': {
      id: '/jornadas/$jornada'
      path: '/jornadas/$jornada'
      fullPath: '/jornadas/$jornada'
      preLoaderRoute: typeof JornadasJornadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/saida-definitiva-do-pais': {
      id: '/guias/saida-definitiva-do-pais'
      path: '/guias/saida-definitiva-do-pais'
      fullPath: '/guias/saida-definitiva-do-pais'
      preLoaderRoute: typeof GuiasSaidaDefinitivaDoPaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/$slug': {
      id: '/guias/$slug'
      path: '/guias/$slug'
      fullPath: '/guias/$slug'
      preLoaderRoute: typeof GuiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acordos/$pais': {
      id: '/acordos/$pais'
      path: '/acordos/$pais'
      fullPath: '/acordos/$pais'
      preLoaderRoute: typeof AcordosPaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hub/': {
      id: '/_authenticated/hub/'
      path: '/hub'
      fullPath: '/hub/'
      preLoaderRoute: typeof AuthenticatedHubIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contato': {
      id: '/api/public/contato'
      path: '/api/public/contato'
      fullPath: '/api/public/contato'
      preLoaderRoute: typeof ApiPublicContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calc-lead': {
      id: '/api/public/calc-lead'
      path: '/api/public/calc-lead'
      fullPath: '/api/public/calc-lead'
      preLoaderRoute: typeof ApiPublicCalcLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hub/leads': {
      id: '/_authenticated/hub/leads'
      path: '/hub/leads'
      fullPath: '/hub/leads'
      preLoaderRoute: typeof AuthenticatedHubLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hub/laudos': {
      id: '/_authenticated/hub/laudos'
      path: '/hub/laudos'
      fullPath: '/hub/laudos'
      preLoaderRoute: typeof AuthenticatedHubLaudosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hub/laudo': {
      id: '/_authenticated/hub/laudo'
      path: '/hub/laudo'
      fullPath: '/hub/laudo'
      preLoaderRoute: typeof AuthenticatedHubLaudoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hub/cupons': {
      id: '/_authenticated/hub/cupons'
      path: '/hub/cupons'
      fullPath: '/hub/cupons'
      preLoaderRoute: typeof AuthenticatedHubCuponsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hub/calculadora': {
      id: '/_authenticated/hub/calculadora'
      path: '/hub/calculadora'
      fullPath: '/hub/calculadora'
      preLoaderRoute: typeof AuthenticatedHubCalculadoraRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hub/blog': {
      id: '/_authenticated/hub/blog'
      path: '/hub/blog'
      fullPath: '/hub/blog'
      preLoaderRoute: typeof AuthenticatedHubBlogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hub/$pais': {
      id: '/_authenticated/hub/$pais'
      path: '/hub/$pais'
      fullPath: '/hub/$pais'
      preLoaderRoute: typeof AuthenticatedHubPaisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/blog-gen': {
      id: '/api/public/hooks/blog-gen'
      path: '/api/public/hooks/blog-gen'
      fullPath: '/api/public/hooks/blog-gen'
      preLoaderRoute: typeof ApiPublicHooksBlogGenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hub/blog/$slug': {
      id: '/_authenticated/hub/blog/$slug'
      path: '/$slug'
      fullPath: '/hub/blog/$slug'
      preLoaderRoute: typeof AuthenticatedHubBlogSlugRouteImport
      parentRoute: typeof AuthenticatedHubBlogRoute
    }
  }
}

interface AuthenticatedHubBlogRouteChildren {
  AuthenticatedHubBlogSlugRoute: typeof AuthenticatedHubBlogSlugRoute
}

const AuthenticatedHubBlogRouteChildren: AuthenticatedHubBlogRouteChildren = {
  AuthenticatedHubBlogSlugRoute: AuthenticatedHubBlogSlugRoute,
}

const AuthenticatedHubBlogRouteWithChildren =
  AuthenticatedHubBlogRoute._addFileChildren(AuthenticatedHubBlogRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedHubPaisRoute: typeof AuthenticatedHubPaisRoute
  AuthenticatedHubBlogRoute: typeof AuthenticatedHubBlogRouteWithChildren
  AuthenticatedHubCalculadoraRoute: typeof AuthenticatedHubCalculadoraRoute
  AuthenticatedHubCuponsRoute: typeof AuthenticatedHubCuponsRoute
  AuthenticatedHubLaudoRoute: typeof AuthenticatedHubLaudoRoute
  AuthenticatedHubLaudosRoute: typeof AuthenticatedHubLaudosRoute
  AuthenticatedHubLeadsRoute: typeof AuthenticatedHubLeadsRoute
  AuthenticatedHubIndexRoute: typeof AuthenticatedHubIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedHubPaisRoute: AuthenticatedHubPaisRoute,
  AuthenticatedHubBlogRoute: AuthenticatedHubBlogRouteWithChildren,
  AuthenticatedHubCalculadoraRoute: AuthenticatedHubCalculadoraRoute,
  AuthenticatedHubCuponsRoute: AuthenticatedHubCuponsRoute,
  AuthenticatedHubLaudoRoute: AuthenticatedHubLaudoRoute,
  AuthenticatedHubLaudosRoute: AuthenticatedHubLaudosRoute,
  AuthenticatedHubLeadsRoute: AuthenticatedHubLeadsRoute,
  AuthenticatedHubIndexRoute: AuthenticatedHubIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CalculadoraRoute: CalculadoraRoute,
  ContatoRoute: ContatoRoute,
  GlossarioRoute: GlossarioRoute,
  LoginRoute: LoginRoute,
  PrecosRoute: PrecosRoute,
  ProfissionalRoute: ProfissionalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AcordosPaisRoute: AcordosPaisRoute,
  BlogSlugRoute: BlogSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  GuiasSlugRoute: GuiasSlugRoute,
  GuiasSaidaDefinitivaDoPaisRoute: GuiasSaidaDefinitivaDoPaisRoute,
  JornadasJornadaRoute: JornadasJornadaRoute,
  SobreDrMarcosRoute: SobreDrMarcosRoute,
  AcordosIndexRoute: AcordosIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  GuiasIndexRoute: GuiasIndexRoute,
  JornadasIndexRoute: JornadasIndexRoute,
  ApiPublicCalcLeadRoute: ApiPublicCalcLeadRoute,
  ApiPublicContatoRoute: ApiPublicContatoRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksBlogGenRoute: ApiPublicHooksBlogGenRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
